import {
  ArrowLeftRight,
  Clapperboard,
  Crop,
  Eraser,
  Film,
  Gauge,
  Grid2x2,
  Hash,
  ImageDown,
  Images,
  type LucideIcon,
  MessageSquareText,
  PartyPopper,
  Rewind,
  RotateCw,
  Scaling,
  Scissors,
  Shrink,
  Smile,
  Type,
  Vibrate,
  WandSparkles,
} from "lucide-react";

/** One lucide icon per tool slug, shared by the home grid and the tool strip. */
export const TOOL_ICONS: Record<string, LucideIcon> = {
  "video-to-gif": Film,
  "gif-to-video": Clapperboard,
  "gif-maker": Images,
  convert: ArrowLeftRight,
  split: Grid2x2,
  resize: Scaling,
  crop: Crop,
  cut: Scissors,
  speed: Gauge,
  reverse: Rewind,
  rotate: RotateCw,
  "add-text": Type,
  effects: WandSparkles,
  "remove-bg": Eraser,
  optimize: Shrink,
  compress: ImageDown,
  intensify: Vibrate,
  party: PartyPopper,
  emojify: Smile,
  number: Hash,
  "text-emoji": MessageSquareText,
};
